#version: '3.3'
services:
  db:
    image: mysql:5.7.16
    env_file:
      - ./.env
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    # restart: always
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  db_data: